In [5]:
import pandas as pd
import time

In [2]:
train_df = pd.read_csv('./data/amex/train_data.csv')

In [7]:
%%time
train_labels_df = pd.read_csv('./data/amex/train_labels.csv')

CPU times: user 210 ms, sys: 613 µs, total: 211 ms
Wall time: 208 ms

In [9]:
%%time
test_df = pd.read_csv('./data/amex/test_data.csv')

CPU times: user 2min 19s, sys: 1min 11s, total: 3min 30s
Wall time: 3min 38s

In [11]:
%%time
train_df.to_feather('train_data')
train_labels_df.to_feather('train_labels')
test_df.to_feather('test_data')

CPU times: user 36.1 s, sys: 8.11 s, total: 44.2 s
Wall time: 12.4 s

In [12]:
train_df.S_2 = pd.to_datetime(train_df.S_2)

In [13]:
all_cols = [c for c in list(train_df.columns) if c not in ['customer_ID','S_2']]

In [14]:
# description
cat_features = ["B_30","B_38","D_114","D_116","D_117","D_120","D_126","D_63","D_64","D_66","D_68"]

In [15]:
num_features = [col for col in all_cols if col not in cat_features]

In [16]:
%%time
train_group_df = train_df.groupby("customer_ID")[num_features].agg(['mean', 'std', 'min', 'max', 'last'])

CPU times: user 19.2 s, sys: 1.52 s, total: 20.7 s
Wall time: 20.7 s

In [17]:
train_group_df.head(2)

                                                         P_2            \
                                                        mean       std
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.933824  0.024194
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.899820  0.022119

                                                                        \
                                                         min       max
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.868580  0.960384
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.861109  0.929122

                                                                  D_39  \
                                                        last      mean
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.934745  0.010704
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.880519  0.215205

                                                                        \
                                                         std       min
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.024444  0.001082
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.199150  0.002224

                                                                        ...  \
                                                         max      last  ...
customer_ID                                                             ...
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.091505  0.009119  ...
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.567403  0.178126  ...

                                                       D_144            \
                                                        mean       std
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.005283  0.002598
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.004218  0.002871

                                                                        \
                                                         min       max
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.000610  0.009616
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.000027  0.009568

                                                                 D_145  \
                                                        last      mean
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.002970  0.005814
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.003169  0.004902

                                                                        \
                                                         std       min
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.003294  0.000995
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.002729  0.000796


                                                         max      last
customer_ID
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fb...  0.009827  0.008533
00000fd6641609c6ece5454664794f0340ad84dddce9a26...  0.009390  0.008514

[2 rows x 885 columns]

In [23]:
%%time

train_group_df.columns = ['_'.join(x) for x in train_group_df.columns]

test_cat_agg = train_df.groupby("customer_ID")[cat_features].agg(['count', 'last', 'nunique'])
test_cat_agg.columns = ['_'.join(x) for x in test_cat_agg.columns]

CPU times: user 3.62 s, sys: 0 ns, total: 3.62 s
Wall time: 3.62 s

In [24]:
test_cat_agg

,B_30_count,B_30_last,B_30_nunique,B_38_count,B_38_last,B_38_nunique,D_114_count,D_114_last,D_114_nunique,D_116_count,...,D_63_nunique,D_64_count,D_64_last,D_64_nunique,D_66_count,D_66_last,D_66_nunique,D_68_count,D_68_last,D_68_nunique
customer_ID,,,,,,,,,,,,,,,,,,,,,
0000099d6bd597052cdcda90ffabf56573fe9d7c79be5fbac11a8ed792feb62a,13,0.0,1,13,2.0,1,13,1.0,1,13,...,1,13,O,1,0,NaN,0,13,6.0,1
00000fd6641609c6ece5454664794f0340ad84dddce9a267a310b5ae68e9d8e5,13,0.0,1,13,2.0,1,13,1.0,1,13,...,1,13,O,1,0,NaN,0,13,6.0,1
00001b22f846c82c51f6e3958ccd81970162bae8b007e80662ef27519fcc18c1,13,0.0,1,13,1.0,1,13,1.0,2,13,...,1,13,R,1,0,NaN,0,13,6.0,1
000041bdba6ecadd89a52d11886e8eaaec9325906c9723355abb5ca523658edc,13,0.0,1,13,2.0,1,13,1.0,1,13,...,1,13,O,1,0,NaN,0,13,3.0,3
00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8ad51ca8b8c4a24cefed,13,0.0,1,13,1.0,2,13,1.0,1,13,...,1,13,O,1,13,1.0,1,13,6.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ffff41c8a52833b56430603969b9ca48d208e7c192c6a4081a6acc28cf4f8af7,13,0.0,1,13,2.0,1,13,0.0,1,13,...,1,13,U,1,13,1.0,1,13,6.0,1
ffff518bb2075e4816ee3fe9f3b152c57fc0e6f01bf7fdd3e5b57cfcbee30286,13,0.0,2,13,7.0,2,13,1.0,1,13,...,1,13,R,1,0,NaN,0,13,6.0,1
ffff9984b999fccb2b6127635ed0736dda94e544e67e026eee4d20f680639ff6,13,0.0,1,13,3.0,2,13,1.0,1,13,...,1,13,U,1,0,NaN,0,13,5.0,1
ffffa5c46bc8de74f5a4554e74e239c8dee6b9baf388145b2c3d01967fcce461,13,0.0,1,13,3.0,1,13,1.0,2,13,...,1,13,U,2,0,NaN,0,13,3.0,2
fffff1d38b785cef84adeace64f8f83db3a0c31e8d92eaba8b115f71cab04681,13,0.0,1,13,3.0,1,13,1.0,1,13,...,1,13,O,2,0,NaN,0,13,5.0,2

In [32]:
missing_df = pd.DataFrame(test_cat_agg.isnull().sum().sort_values(ascending=False)/len(test_cat_agg), columns=['percentage'])
missing_df

               percentage
D_66_last        0.869744
D_64_last        0.011503
D_68_last        0.011442
D_120_last       0.010327
D_117_last       0.010327
D_114_last       0.010327
D_116_last       0.010327
B_38_last        0.000068
B_30_last        0.000068
D_63_count       0.000000
D_63_last        0.000000
D_63_nunique     0.000000
D_64_nunique     0.000000
D_64_count       0.000000
D_126_last       0.000000
D_66_count       0.000000
D_66_nunique     0.000000
D_68_count       0.000000
D_126_nunique    0.000000
B_30_count       0.000000
D_126_count      0.000000
D_120_nunique    0.000000
D_120_count      0.000000
D_117_nunique    0.000000
D_117_count      0.000000
D_116_nunique    0.000000
D_116_count      0.000000
D_114_nunique    0.000000
D_114_count      0.000000
B_38_nunique     0.000000
B_38_count       0.000000
B_30_nunique     0.000000
D_68_nunique     0.000000